CREATE TABLE industries
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(100) NOT NULL,
    name   VARCHAR(255) NOT NULL,
    active BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_industries_code UNIQUE (code)
);

CREATE TABLE specializations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    industry_id BIGINT       NOT NULL,
    code        VARCHAR(100)  NOT NULL,
    name        VARCHAR(255)  NOT NULL,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_specializations_code
        UNIQUE (code),

    CONSTRAINT uk_specializations_industry_name
        UNIQUE (industry_id, name),

    CONSTRAINT fk_specializations_industry
        FOREIGN KEY (industry_id)
            REFERENCES industries (id)
);