CREATE TABLE companies
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    description    TEXT,
    industry_id    BIGINT       NOT NULL,
    country        VARCHAR(100) NOT NULL,
    city           VARCHAR(150) NOT NULL,
    established_at DATE,
    capabilities   TEXT,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_companies_industry
        FOREIGN KEY (industry_id)
            REFERENCES industries (id)
);

CREATE TABLE company_specializations
(
    company_id        BIGINT NOT NULL,
    specialization_id BIGINT NOT NULL,

    CONSTRAINT pk_company_specializations
        PRIMARY KEY (company_id, specialization_id),

    CONSTRAINT fk_company_specializations_company
        FOREIGN KEY (company_id)
            REFERENCES companies (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_company_specializations_specialization
        FOREIGN KEY (specialization_id)
            REFERENCES specializations (id)
);