@startuml
title Proces dopasowania ofert i potrzeb
!pragma layout smetana

start
:Pobierz aktywne potrzeby i oferty;
:Utwórz problem dopasowania;
:Wygeneruj rankingi potrzeb względem ofert;
:Wygeneruj rankingi ofert względem potrzeb;
:Utwórz pojemności uczestników;

while (Są jeszcze wolni uczestnicy?) is (tak)
  partition "Gale-Shapley" {
    :Wybierz uczestnika bez pełnego dopasowania;
    :Złóż propozycję najlepszemu kandydatowi;
    if (Kandydat jest kompatybilny?) then (tak)
      if (Kandydat ma wolną pojemność?) then (tak)
        :Dodaj dopasowanie;
      else (nie)
        :Porównaj z najgorszym aktualnym dopasowaniem;
        if (Nowa propozycja jest lepsza?) then (tak)
          :Zamień dopasowanie;
        else (nie)
          :Odrzuć propozycję;
        endif
      endif
    else (nie)
      :Odrzuć propozycję;
    endif
  }
endwhile (nie)

:Zwróć listę dopasowanych par;
stop
@enduml
